OPXwx.ai services Integration Completed
ibm-client-engineering/solution-openpages-wxai-translation pull request #18
Opened 2024-12-23 21:59 UTC by alinibm

Finished documenting the integration between OpenPages and the wastonx.ai service.

2025-01-02 16:08 UTC, eashantIBM requested changes
Looks really good! Just a few lil things to modify:

- Lets move all the images to the images folder in the repo rather than the git links.
- Can we make your edits in the "prepare" section to be under OpenPages as a whole and just denote it with Techzone. Feel free to make the line 11 (### IBM OpenPages) H2.

2025-01-02 20:58 UTC, alinibm commented
Changes as been made as requested. Let me know if there is anything else.

2025-01-02 22:03 UTC, eashantIBM approved these changes
This looks amazing!! Thank you!

2025-01-03 19:32 UTC, eashantIBM approved these changes
Looks good to me!

2025-01-03 19:38 UTC, merged